### ISSUE TITLE
you guys said the tags not showing in 1.7-1.20.1 was fixed but not even vanilla tags show anymore?

### ISSUE THREAD

**Issue by pqvo13** [Netiyiy/TierTagger#16]

**Comment by pqvo13** [comment]
Is essentials supported with this or no? because if it isn't thats probably the problem

**Comment by pqvo13** [comment]
nope I checked with someone that is tiered officially and it doesn't come up

**Comment by uku3lig** [comment]
1. the issue was closed because i added code that fixed the issue; however, since i have more stuff that i want to add, and since it's the holiday season and i am visiting family, i haven't had the time yet to add those things and publish a release on modrinth (especially since i need to backport the fix to 5 different minecraft versions, which takes time)

2. vanilla tiers don't show anymore because due to apparently "extremely abusive behavior" from tiertagger, the api used was changed in a way that breaks everything!

3. yes, this is compatible with essential, it doesn't interfere with tiertagger or any of my mods

**Comment by pqvo13** [comment]
ohhh alright thanks
